# .github/workflows/release.yml

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build_windows:
    name: build windows
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          use-cross: true
      - name: Archive chrome production zip file
        uses: actions/upload-artifact@v2
        with:
          name: alby.exe
          path: target/release/alby.exe

  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          PRE_BUILD: pre.sh
          RUSTFLAGS: "-Clink-arg=-lssp_nonshared -Clink-arg=-lssp -ladvapi32"
